### ISSUE TITLE
Key Exporting

### ISSUE THREAD

**Issue by ryanjagar** [ytgov/eco-asset-tracker#100]
As a user I would like to export the list data so that I can create my own spreadsheet to use or provide to another person

**Comment by ryanjagar** [comment]
With @dpdavids for decision.

**Comment by ryanjagar** [comment]
@dpdavids Here a screen shot of an alternative location for the download button.  Let me know which you prefer.
<img width="982" alt="alternate download button location" src="https://user-images.githubusercontent.com/49032969/197807040-a7e3242d-360b-43a0-a85e-a756c76e1af2.png">

**Comment by dpdavids** [comment]
@ryanjagar I like the top right.

**Comment by dpdavids** [comment]
not able to save any key records (on hitting create button nothing happens)...502 error in firebug

**Comment by ryanjagar** [comment]
@dpdavids would you try this and let me know if the issue is resolved.
