### ISSUE TITLE
Add infrastructure to a Room

### ISSUE THREAD

**Issue by ryanjagar** [ytgov/eco-asset-tracker#68]
As a user I would like to add infrastructure to a room so that I can tell what infrastructure is available in the room so that making a decision about who to assign is easier

**Comment by ryanjagar** [comment]
Infrastructure is a sub-set of assets.  Infrastructure can be assigned to a room via the _Assets_ page.  A list of infrastructure assigned to the room is available on the _Room Detail_ page.

**Comment by dpdavids** [comment]
off of the Room details screen (similar to assets region) can you add a + to the infrastructure card that allows a user to add an infrastructure from the room details screen.  Infrastructure features should  not appear on the assets region.
