### ISSUE TITLE
Key Search (Global)

### ISSUE THREAD

**Issue by ryanjagar** [ytgov/eco-asset-tracker#97]
As a user I would like to input a keyword and search the entire dataset so that I can find relevant records (Global search)

**Comment by ryanjagar** [comment]
Bug: Search does not include Room Name

**Comment by ryanjagar** [comment]
Further testing indicates this working.

**Comment by dpdavids** [comment]
not able to save any key records (on hitting create button nothing happens)...502 error in firebug

**Comment by ryanjagar** [comment]
@dpdavids would you give this a shot and let me know if it's fixed.
